/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sales.view;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.sales.controller.ProductDAO;
import org.sales.controller.SalesDAO;
import org.sales.model.Product;
import org.sales.model.Table;
import org.sales.util.Global;

/**
 *
 * @author fox
 */
public class SellProduct extends javax.swing.JInternalFrame {

    /**
     * Creates new form SellProduct
     */
    DefaultTableModel model;//to obtain the table in sele product 
    private void printBill(){
        int count=jTable_Sales.getRowCount();
        String str="Namaste Super Market\nNewRoad,Kathmandu\n";
        for(int i=0;i<count;i++){
            str+=jTable_Sales.getValueAt(i,0).toString()+"";
             str+=jTable_Sales.getValueAt(i,1).toString()+"";
            str+=jTable_Sales.getValueAt(i,2).toString()+"";
            str+=jTable_Sales.getValueAt(i,3).toString()+"";
            str+=jTable_Sales.getValueAt(i,4).toString()+"\n";

        }
        str+="Grand Total:"+jLabel_Total.getText();
        str+="\nThank you For Visiting!!!";
        
        BillPrint ob=new BillPrint();
        ob.jTextArea_Bill.setLineWrap(true);
        ob.jTextArea_Bill.setText(str);
        try{
            ob.jTextArea_Bill.print();
        }
        catch(Exception ex){
            System.out.println(ex);
        }
    }
    
    
    public SellProduct() {
        initComponents();
        jLabel_CurrentDate.setText(new Date().toString());
        jLabel_User.setText(Global.user);
        model=new DefaultTableModel(null,new String[]{"Id","Name","Price","Qty","Total"});
        jTable_Sales.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Sales = new javax.swing.JTable();
        jTextField_Id = new javax.swing.JTextField();
        jLabel_GrandTotal = new javax.swing.JLabel();
        jLabel_Total = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_User = new javax.swing.JLabel();
        jButton_SavePrint = new javax.swing.JButton();
        jLabel_CurrentDate = new javax.swing.JLabel();

        jLabel1.setText("Id");

        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jTable_Sales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_Sales);

        jTextField_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IdActionPerformed(evt);
            }
        });

        jLabel_GrandTotal.setText("Grand Total");

        jLabel_Total.setText("total");

        jLabel3.setText("Logged in as:");

        jLabel_User.setText("user");

        jButton_SavePrint.setText("Save and Print");
        jButton_SavePrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SavePrintActionPerformed(evt);
            }
        });

        jLabel_CurrentDate.setText("Current Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Delete)
                .addGap(148, 148, 148))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel_GrandTotal)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel_Total))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel_User)
                                .addGap(103, 103, 103)
                                .addComponent(jButton_SavePrint))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel_CurrentDate)))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_CurrentDate)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton_Delete)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_GrandTotal)
                    .addComponent(jLabel_Total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel_User)
                    .addComponent(jButton_SavePrint))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void calculateTotal(){
    int rows=jTable_Sales.getRowCount();
    double gTotal=0.0;
    for(int i=0; i<rows;i++){
        double total=Double.parseDouble(jTable_Sales.getValueAt(i,4).toString());
        gTotal+=total;
    }
    jLabel_Total.setText(gTotal+"");
}
    private void jTextField_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IdActionPerformed
        // TODO add your handling code here:
        int id=Integer.parseInt(jTextField_Id.getText());
        ProductDAO pDAO=new ProductDAO();
        Product ob=pDAO.fetchData(id);//fn call grera id pass gryo
        if(ob.getId()>0){
            
        
        model.addRow(new Object[]{ob.getId(),ob.getName(),ob.getPrice(),"1",ob.getPrice()});
        calculateTotal();
    }//GEN-LAST:event_jTextField_IdActionPerformed
    }
    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        // TODO add your handling code here:
        int row=jTable_Sales.getSelectedRow();
        model.removeRow(row);
        calculateTotal();
        
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_SavePrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SavePrintActionPerformed
        // TODO add your handling code here:
        List <Table> list = new ArrayList();
        int count = jTable_Sales.getRowCount();
        for(int i = 0; i<count; i++){
            Table ob = new Table();
            int pid = Integer.parseInt(jTable_Sales.getValueAt(i, 0).toString());
            int sid = Global.uid;
            int qty = Integer.parseInt(jTable_Sales.getValueAt(i, 3).toString());
            Date d = new Date();
            ob.setPid(pid);
            ob.setSid(sid);
            ob.setQty(qty);
            ob.setDate(d);
            list.add(ob);
        }
        SalesDAO sDAO=new SalesDAO();
        sDAO.saveData(list);
        printBill();
    }//GEN-LAST:event_jButton_SavePrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_SavePrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_CurrentDate;
    private javax.swing.JLabel jLabel_GrandTotal;
    private javax.swing.JLabel jLabel_Total;
    private javax.swing.JLabel jLabel_User;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Sales;
    private javax.swing.JTextField jTextField_Id;
    // End of variables declaration//GEN-END:variables
}
